
java_binary (
    name = "BazelApp",
    srcs = glob(["src/main/java/com/surya/*.java"]),
    main_class = "com.surya.BazelApp",
    deps = ["//bazelgreeting:greeter", "@maven//:org_apache_commons_commons_lang3"]
)
