server:
  port : 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3305/customerdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          time_zone: UTC