toDoEndpoint: https://jsonplaceholder.typicode.com
postEndpoint: https://jsonplaceholder.typicode.com
environmentName: ${ENV_NAME}
toDoCredentials:
  username: surya
  password: ${TODO_PASSWORD:-password}
postCredentials:
  username: surya
  password: ${POST_PASSWORD:-password}
